#!/bin/bash
#an example of sbatch file to submit mintegrate_par job
#Jie Nan at MAXIV, 12/2016
#jie.nan@maxiv.lu.se

#SBATCH -t 00:10:00

# job id

# filenames stdout and stderr - customise, include %j
#SBATCH -o mintegrate_%j.out
#SBATCH -e mintegrate_%j.err
#SBATCH --exclusive



# write this script to stdout-file - useful for scripting errors
cat $0

# load the modules required for you program - customise for your program
export PATH="$MX_SOFT/XDS:$PATH"

image1=$1
nitask=$2
itask=$3
nbatask=$4
echo `pwd` $image1 $nitask $itask $nbatask >> jobs.log
echo $image1 $nitask $itask $nbatask | mintegrate_par
