#!/bin/bash
#an example of sbatch file to submit mcolspot_par job
#Jie Nan at MAXIV, 12/2016
#jie.nan@maxiv.lu.se

#SBATCH -t 00:10:00

# job id

# filenames stdout and stderr - customise, include %j
#SBATCH -o mcolspot_%j.out
#SBATCH -e mcolspot_%j.err
#SBATCH --exclusive

# write this script to stdout-file - useful for scripting errors
cat $0

# load the modules required for you program - customise for your program
export PATH="/home/jienan/bin/xtal/XDS:$PATH"

itask=$1
echo $itask >> jobs.log
echo $itask | mcolspot_par
