#!/bin/bash
# Jie Nan, 08/2019
# for running XDS on MAXIV HPC from CC computer
process_dir=`pwd`
ssh -tq -o "BatchMode yes" $HPC_HOST "cd $process_dir;pwd; sbatch /mxn/groups/sw/mxsw/XDS/xds.sh >current_job"
current_job=`awk '/Submitted batch job/ {print $4}' current_job`
# in case of ctrl+c or kill, cancel the slurm job

function kill_job()
{
   ssh -tq -o "BatchMode yes" $HPC_HOST "scancel $1"
   if [ -f "current_subjob" ]
   then
       current_subjob=`cat current_subjob`
       if [ ! -z "$current_subjob" ]
       then
          ssh -tq -o "BatchMode yes" $HPC_HOST "scancel $current_subjob"
       fi
   fi
}

trap "kill_job $current_job" SIGINT SIGTERM #2 15

TIMEOUT=600
t_count=0
t_sleep=2
slurm_output="xds_hpc_$current_job.out"
#send the output to the terminal screen until the script stops
tail --retry -f $slurm_output --pid=$$ &

while [ $t_count -lt $TIMEOUT ]
do
  ssh -tq -o "BatchMode yes" $HPC_HOST "squeue -j $current_job -h >$process_dir/current_job.status"
  #ssh cn2 "squeue -j $current_job -h >$process_dir/current_job.status"
  current_job_status=$(<current_job.status)
  if [[ $current_job_status = "" ]]
    then break
  fi
 sleep $t_sleep
 t_count=`expr $t_count + $t_sleep`
done

rm current_job
